### ISSUE TITLE
ReactivePhoneFormField  - Validation issue

### ISSUE THREAD

**Issue by cto-atisaral** [artflutter/reactive_forms_widgets#20]
control validation state is not reflected properly. 

control.valid is true even if I enter a 2 digit mobile number. (The underlying widget does validate properly)

Also, autovalidateMode is hardcoded to disabled.

**Comment by vasilich6107** [comment]
@cto-atisaral the validation handling is on the reactive_forms engine. This is why there is no need on autovalidation
Use validators array to specify any validators you need.

**Comment by vasilich6107** [comment]
Refer to the validation section of the docs for more info

https://github.com/joanpablo/reactive_forms#what-about-validators

**Comment by cedvdb** [comment]
There is indeed a validation issue compared to the original library.

That is `phone_form_field` exports a set of validators:

# Built-in validators
required : PhoneValidator.required
valid : PhoneValidator.valid (default value when no validator supplied)
valid mobile number : PhoneValidator.validMobile
valid fixed line number : PhoneValidator.validFixedLine
valid type : PhoneValidator.validType
valid country : PhoneValidator.validCountry
none : PhoneValidator.none (this can be used to disable default valid validator)


The wrapper does not overwrite the validator with `PhoneValidator.none` and thus the default valid validator is used. Furthermore the error message is not displayed the same as using the vanilla library.

Phone validation is not something that is simple, especially when checking if it's a valid mobile phone number so I'd expect user to use the validators furnished by the phone_form_field library instead of rolling their own.

**Comment by cto-atisaral** [comment]
yeah I get your point.


class CustomReactiveValidators {
  static Map<String, dynamic>? validPhoneNumber(
      AbstractControl<dynamic> control) {
    if (control.value == null) {
      return null;
    }
    if (control.value! is! PhoneNumber) {
      return null;
    }
    if (!(control.value as PhoneNumber).validate()) {
      return {CustomValidationMessage.invalidPhone: true};
    }
  }
}

class CustomValidationMessage {
  static const String invalidPhone = 'invalidPhone';
}


I am using the below solution now

**Comment by vasilich6107** [comment]
Closing this issue

**Comment by cedvdb** [comment]
The default behavior of the wrapper is a bit faulty though, as the error message displayed seems to be wonky

**Comment by taskindrp** [comment]
> There is indeed a validation issue compared to the original library.
> 
> That is `phone_form_field` exports a set of validators:
> 
> # Built-in validators
> required : PhoneValidator.required valid : PhoneValidator.valid (default value when no validator supplied) valid mobile number : PhoneValidator.validMobile valid fixed line number : PhoneValidator.validFixedLine valid type : PhoneValidator.validType valid country : PhoneValidator.validCountry none : PhoneValidator.none (this can be used to disable default valid validator)
> 
> And the reactive wrapper does not exports such validators. Phone validation is not something that is simple, especially when checking if it's a valid mobile phone number so I'd expect users to use the validators furnished by the phone_form_field library instead of rolling their own. Not having those validators usable is not a great option.
> 
> Also, the wrapper does not overwrite the validator with `PhoneValidator.none` and thus the default valid validator is used. Furthermore the error message is not displayed the same as using the vanilla library.
> 
> One way to handle this is to "convert" those built in validators from the phone_form_field library to ones that are usable in your project.
> 
> I'd suggest (not tested):
> 
> ```dart
> final phoneCtrl = FormControl<PhoneNumber>(
>   value: null,
>   validators: [
>     AppValidators.toRxFormValidator(
>       PhoneValidator.compose([
>         PhoneValidator.required(),
>         PhoneValidator.validMobile(),
>       ])
>     ),
>   ],
> );
> 
> class AppValidators {
> 
>   static toRxFormValidator<T>(String? Function(T) validator) {
>     return (ctrl) {
>       final error = validator(ctrl.value);
>       return error != null ? <String, dynamic>{error: true} : null;
>     };
>   }
> }
> ```
> 
> Although, this is quite ugly compared to using the vanilla:
> 
> ```dart
> PhoneValidator.compose([
>     PhoneValidator.required(),
>     PhoneValidator.validMobile(),
>   ])
> ```

this does not work anymore following error is given:

```
type '(dynamic) => String?' is not a subtype of type 'Validator<dynamic>'
```

anyway to fix this?
